### PR TITLE
chore: migrate to boxo

### PR DESCRIPTION
**Pull request by Jorropo**
This is required because of the cyclic module dependencies, this will fix CI for https://github.com/ipfs/kubo/pull/9680.

### CODE REVIEW

**Comment by BigLep** [comment]
@Jorropo : is this still needed?  Which iteration should this be in?

**Comment by Jorropo** [comment]
@BigLep we can do this once released.

**Comment by willscott** [comment]
can we update this to refer to the current boxo release?

**Comment by Jorropo** [comment]
To help in lotus we would need https://github.com/filecoin-project/lotus/pull/10562

**Review by guseggert — APPROVED** [review]

**Pull request merged**
